### ISSUE TITLE
Conflicting PGPASSWORD env var on Windows

### ISSUE THREAD

**Issue by bkoelman** [ikalnytskyi/action-setup-postgres#17]
As can be seen [here](https://github.com/npgsql/npgsql/blob/main/.github/workflows/build.yml#L21-L23), the `PGPASSWORD` environment variable is defined on Windows. Its [default value](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#postgresql) of `root` conflicts with the default value `postgres` from `action-setup-postgres`. So it would be nice to set this variable accordingly from this GitHub action. It took me several hours to figure this out, as I couldn't find why our tests failed.

**Comment by bkoelman** [comment]
This applies to `PGUSER` as well; see https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers/Install-PostgreSQL.ps1#L6-L7. Linux and macOS do not set these environment variables.

**Comment by ikalnytskyi** [comment]
Hey @bkoelman,

Thank you for reporting. I'm sorry I got to your issue 4 months after it was reported.

I deliberately decided that I don't want to set `PGUSER`, `PGPASSWORD` and `PGHOST` for the rest of the job since it may have undesired consequences similar to what you have reported, especially when someone is looking to deal with multiple PostgreSQL users. It's advised to opt into superuser using a service name  or a connection uri exposed by this action explicitly. See https://github.com/ikalnytskyi/action-setup-postgres/commit/75b3f77472f7da5a057eaf58267d0eee259afd33 for details. Setting PGUSER and PGPASSWORD would be a step backward.

The README file for the Windows runner says nothing about setting PGPASSWORD (see EnvironmentVariables property), but as you pointed out, their installation script [does it](https://github.com/actions/runner-images/blob/266f9413d39fc77ade974757b633ef98873c9c21/images/windows/scripts/build/Install-PostgreSQL.ps1#L80-L82) anyway. I'm not sure what to do here, to be honest. We can document this as a known gotcha, or simply "unset" the environment variable to make behavior consistent between OS-es. Let me think about it.
