### ISSUE TITLE
v5 does not unset PG* environment variables

### ISSUE THREAD

**Issue by bkoelman** [ikalnytskyi/action-setup-postgres#24]
The release notes for v5 mention that it unsets PG* environment variables. I've tried this on Windows. It turns out the variables are set to an empty string instead of being unset.

After running your action, the next powershell script:
```
Get-ChildItem env:* | Sort-Object Name | Format-List
```
includes the following entries:
![image](https://github.com/ikalnytskyi/action-setup-postgres/assets/10324372/355e9134-3f59-4d98-a1e8-0a4bfee73f85)

As a result, 3rd party libs/tools that check for the existence of the variable and use it when present won't work properly.

Is there a way to truly unset them, instead of setting them to an empty string?

**Comment by ikalnytskyi** [comment]
Unfortunately, GitHub Actions doesn't support _unsetting_ environment variables. The best we can do in this case is to set those we don't need to nullify their values to avoid any confusion (e.g. when PGUSER is set to a wrong value).

The [Usage](https://github.com/ikalnytskyi/action-setup-postgres?tab=readme-ov-file#usage) section in README now contains a note that warns users that they are recommended to use the `connection-uri` output parameter or `PGSERVICE=postgres` environment variable.

I'm sorry, I don't think I can do more at the moment. As I mentioned in the previous issue, I deliberately don't want to set `PGUSER`, `PGPASSWORD` and other environment variables. I want consumers to be explicit about PostgreSQL users they want to use, and using `connection-uri` output parameter of `PGSERVICE` is easy enough in order to do not decline user experience.

**Comment by bkoelman** [comment]
Thanks for looking into this. It's good to know that there's no better way, so the current behavior makes sense.

I don't understand why you're against setting PGUSER/PGPASSWORD. There are many systems out there that consume them. What's wrong with facilitating that?
