### ISSUE TITLE
Windows: invalid locale name "en_US.UTF-8"

### ISSUE THREAD

**Issue by irenarindos** [ikalnytskyi/action-setup-postgres#25]
On Windows runners I'm intermittently seeing the following error:

`initdb: error: invalid locale name "en_US.UTF-8"`

A possible solution is to remove the locale param for `initdb` and allow the runner to use the environment's locale.

**Comment by ikalnytskyi** [comment]
Hey @irenarindos,

Sorry for taking so long to get back to you. Can you please clarify the windows runner version you are experiencing this issue with? If it's a public repository, is there any link to the failed job I can inspect?

I can't see any issues with `windows-latest` runner we're using in CI in this repository. It just [works](https://github.com/ikalnytskyi/action-setup-postgres/actions/runs/8311064035/job/22744270028#step:3:101) and gives you:

```
The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".
```

**Comment by ikalnytskyi** [comment]
I think I managed to [reproduce](https://github.com/ikalnytskyi/action-setup-postgres/actions/runs/8335795401/job/22811898934?pr=30#step:3:101) the issue on Windows 2019 runners. I'll think what I can do here. Removing the encoding from `initdb` should be the action of last resort, since I aim to have the same PostgreSQL environment across all supported operating systems.
