### ISSUE TITLE
Unset PGSERVICEFILE by default?

### ISSUE THREAD

**Issue by chiroptical** [ikalnytskyi/action-setup-postgres#40]
https://github.com/ikalnytskyi/action-setup-postgres/blob/687404e7b78b0b3471751635e69f70d54a09d6e7/action.yml#L127

Hello, I am trying to use this action to set up `dbmate` and getting the following

```
panic: setting PGSERVICEFILE not supported
```

It might be nice to disable this by default since unsetting environment variables is impossible. We can always set this `env` variable ourselves using the outputs.

**Comment by ikalnytskyi** [comment]
Hey @chiroptical,

Thank you for reporting this. This sounds like a bug in `dbmate`, since unless `PGSERVICE` is set (and this action doesn't set it), `PGSERVICEFILE` should not be used. I'd recommend to file an issue for `dbmate`. At the very least we can let them know about it.

As for your suggestion, I definitely would prefer keeping things simpler for end users, and not asking them to set both `PGSERVICE` and `PGSERVICEFILE` simultaneously. Not saying that such change is backward incompatible by nature.

What I can consider is switching to default `PGSERVICEFILE` location, so I won't need to set `PGSERVICEFILE` in the action. Since location is user-depended and is different on Windows, at the time I set the environment variable to simplify implementation details.

**Comment by ikalnytskyi** [comment]
It seems `dbmate` uses `lib/pq` to deal with PostgreSQL, and `lib/pq` simply [panics](https://github.com/lib/pq/blob/3d613208bca2e74f2a20e04126ed30bcb5c4cc27/conn.go#L2044-L2045) if one of the known environment variables is set but are not supported. It's unfortunate that authors didn't provide a way to bypass it, especially for optional client-side environment variables such as `PGSERVICEFILE`.

At this moment I'm not sure how to proceed, since moving `pg_service.conf` to the system-wide location requires setting `PGSYSCONFDIR` which [panics](https://github.com/lib/pq/blob/3d613208bca2e74f2a20e04126ed30bcb5c4cc27/conn.go#L2076-L2077) too. It seems the development of `lib/pq` is rather abandoned (save for bugfixes which this doesn't fall under) in favor of the `pgx` driver.

I need to think it through. It'd be unfortunate to introduce a backward incompatible change and give up on a simple _service_ usage just to support one broken driver.

As a workaround, I'd probably suggest running `dbmate` like this:

```yaml
run: |
    unset PGSERVICEFILE
    dbmate args...
```

**Comment by chiroptical** [comment]
Hey, thanks so much for such a detailed response. I was on vacation so slow to respond.

> As a workaround, I'd probably suggest running dbmate like this:

Yeah, this works relatively well. I am just spinning up a bunch of databases and running dbmate in my tests so I have to be concerned about this in a few places.

> I need to think it through. It'd be unfortunate to introduce a backward incompatible change and give up on a simple service usage just to support one broken driver.

I totally agree with you here. Happy with whatever you decide :smile:

**Comment by ikalnytskyi** [comment]
I'm about to make a new release, and I decided to close this issue. At the moment I'd rather let dbmate users to do `unset PGSERVICEFILE` before execution, than introduce a backward incompatible change just to workaround the broken driver dbmate use. If more users report issues with `PGSERVICEFILE`, I'll definitely reconsider this.
